# Site
title: Pigs-UI #标题
subtitle: welcome to Pigs-UI
description: UI Library for Nerv
author: sunyuhang
language: zh-CN
timezone:

# URL
url: https://sunyuhang404.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:


# Extensions
theme: hexo-theme-landfarz   #主题设置

# Deployment
deploy:
  type: git
  repo: https://github.com/sunyuhang404/pigs-ui.git
  branch: master